import type { Metadata } from "next";

import Header from "@/components/header";

import "@/styles/globals.css";
import "@/styles/reset.css";

import * as styles from "@/styles/layout.css";

// TODO: Use Vanilla Extract's `fontFace` API
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <Header />

        <main className={styles.container}>{children}</main>

        <footer></footer>
      </body>
    </html>
  );
}
